version: '3.6'

services:
  webserver:
    build:
      context: ./bin/${PHPVERSION}
    container_name: '${COMPOSE_PROJECT_NAME}_php'
    restart: always
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${VHOSTS_DIR}:/etc/apache2/sites-available
      - ${APACHE_LOG_DIR}:/var/log/apache2
    ports:
      - ${INTERFACE}:${HOST_MACHINE_UNSECURE_HOST_PORT}:80
      - ${INTERFACE}:${HOST_MACHINE_SECURE_HOST_PORT}:443
    depends_on:
      - mysql
    networks:
      bitrix:
        ipv4_address: 172.16.238.2
  mysql:
    build:
      context: ./bin/${DATABASE}
    container_name: '${COMPOSE_PROJECT_NAME}_database'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${INTERFACE}:${HOST_MACHINE_MYSQL_PORT}:3306
    volumes:
      #      Можно смонтировать базу на папку, чтобы она не удалялась при удалении контейнера
      #      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      bitrix:
        ipv4_address: 172.16.238.3
  pma:
    # используем готовый образ phpmyadmin
    image: phpmyadmin
    container_name: '${COMPOSE_PROJECT_NAME}_phpMyAdmin'
    restart: always
    ports:
      - ${INTERFACE}:${HOST_MACHINE_PMA_PORT}:80
    depends_on:
      - mysql
    environment:
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ARBITRARY: 1
      PMA_HOST: ${COMPOSE_PROJECT_NAME}_database
    networks:
      bitrix:
        ipv4_address: 172.16.238.4
networks:
  bitrix:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24